# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[cmd_duration]
disabled = true

[gcloud]
symbol = '☁️ ' 
format = '[$symbol$project]($style) '
style = 'bold #84aebb'
disabled = true

[username]
style_user = "bold fg:#99cccc"
format = "[$user]($style) "
disabled = false
show_always = false

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"
time_range = "00:00:00-00:00:00"
style = 'bold cyan'

[git_branch]
style = 'bold #fbcbe2'

[directory]
truncation_length	= 1
style = 'bold blue'
